version: "3.9"
services:
  python:
    image: zarbose/ec2-python
    container_name: python
    env_file:
      - secrets/.env_python
    ports:
      - "8000:8000"
    networks:
      - python
    depends_on:
      - influxdb

  influxdb:
    image: zarbose/ec2-influxdb
    container_name: influxdb
    env_file:
      - secrets/.env_influxdb
    ports:
      - "8086:8086"
    networks:
      - python
      - grafana

  grafana:
    image: zarbose/ec2-grafana
    container_name: grafana
    env_file:
      - secrets/.env_gf
    ports:
      - "3000:3000"
    networks:
      - grafana
    depends_on:
      - influxdb
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/

networks:
  python:
  grafana: