version: "3.7"
services:
  django:
    build:
      context: ./
      dockerfile: django.Dockerfile
    ports:
      - "8000:8000"
    networks:
      - influxdb
      - django
    depends_on:
      - influxdb

  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    networks:
      - influxdb
      - django
      - grafana
    volumes:
      - "db-data:/var/lib/influxdb2"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - grafana
    depends_on:
      - influxdb


networks:
  django:
  influxdb:
  grafana:

volumes:
  db-data:
