version: "3.8"
services:
  python:
    build:
      context: ./
      dockerfile: python.Dockerfile
    image: ec2-python
    container_name: python
    ports:
      - "8000:8000"
    networks:
      - influxdb
      - python
    depends_on:
      - influxdb
    volumes:
      - "./Script:/home/data"

  influxdb:
    build:
      context: ./
      dockerfile: influxdb.Dockerfile
    image: ec2-influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      - influxdb
      - python
      - grafana
    # volumes:
    #   - "influx-data:/var/lib/influxdb2"

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - grafana
    depends_on:
      - influxdb
    # volumes:
    #   - "grafana-data:/var/lib/grafana"


networks:
  python:
  influxdb:
  grafana:

volumes:
  influx-data:
  grafana-data:
