version: "3.8"
services:
  django:
    build:
      context: ./
      dockerfile: django.Dockerfile
    image: ec2-django
    container_name: django
    ports:
      - "8000:8000"
    networks:
      - influxdb
      - django
    depends_on:
      - influxdb

  influxdb:
    build:
      context: ./
      dockerfile: influxdb.Dockerfile
    image: ec2-influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      - influxdb
      - django
      - grafana
    volumes:
      - "db-data:/var/lib/influxdb2"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - grafana
    depends_on:
      - influxdb


networks:
  django:
  influxdb:
  grafana:

volumes:
  db-data:
