version: "3.9"
services:
  python:
    build:
      context: ./
      dockerfile: python.Dockerfile
    image: ec2-python
    container_name: python
    ports:
      - "8000:8000"
    networks:
      - python
    depends_on:
      - influxdb
    # volumes:
    #   - "./Script:/home/data"

  influxdb:
    build:
      context: ./
      dockerfile: influxdb.Dockerfile
    image: ec2-influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      - python
      - grafana
    # environment:
      # DOCKER_INFLUXDB_INIT_USERNAME: /run/secrets/admin_login
      # DOCKER_INFLUXDB_INIT_PASSWORD: /run/secrets/admin_password
      # DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: /run/secrets/token
    # secrets:
      # - admin_login
      # - admin_password
      # - token
    # volumes:
    #   - "influx-data:/var/lib/influxdb2"

  grafana:
    build:
      context: ./
      dockerfile: grafana.Dockerfile
    image: ec2-grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - grafana
    depends_on:
      - influxdb
    # volumes:
    #   - "grafana-data:/var/lib/grafana"

# secrets:
  # admin_login:
  #   file: admin_login.txt
  # admin_password:
  #  file: admin_password.txt
  # token:
  #  file: token.txt

networks:
  python:
  grafana:

volumes:
  influx-data:
  grafana-data:
