version: "3.9"
services:
  python:
    build:
      context: ./
      dockerfile: python.Dockerfile
    image: zarbose/ec2-python
    container_name: python
    env_file:
      - secrets/.env_python
    ports:
      - "8000:8000"
    networks:
      - python
    depends_on:
      - influxdb

  influxdb:
    build:
      context: ./
      dockerfile: influxdb.Dockerfile
    image: zarbose/ec2-influxdb
    container_name: influxdb
    env_file:
      - secrets/.env_influxdb
    ports:
      - "8086:8086"
    networks:
      - python
      - grafana

  grafana:
    build:
      context: ./
      dockerfile: grafana.Dockerfile
    image: zarbose/ec2-grafana
    container_name: grafana
    env_file:
      - secrets/.env_gf
    ports:
      - "3000:3000"
    networks:
      - grafana
    depends_on:
      - influxdb

networks:
  python:
  grafana: