{
 "title": "Simulation",
 "time": { "from": "now/d", "to": "now/d" },
 "panels": [
  {
   "title": "Prix du jour",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "€/MWh" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket:\"price\")\n|> range(start: today(), stop: date.add(d: 24h, to: today()))\n|> filter(fn:(r) => r._measurement == \"cout-electricite\")\n|> filter(fn:(r) => r.location == \"France\")\n|> filter(fn:(r) => r._field == \"euros\")"
    }
   ]
  },
  {
   "title": "Prix moyen de la journée",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\nfrom(bucket:\"price\")\r\n|> range(start: today(), stop: date.add(d: 24h, to: today()))\r\n|> filter(fn:(r) => r._measurement == \"cout-electricite\")\r\n|> filter(fn:(r) => r.location == \"France\")\r\n|> filter(fn:(r) => r._field == \"euros\")\r\n|> mean()"
    }
   ]
  },
  {
   "title": "Rendement",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket:\"price\")\n|> range(start: today(), stop: date.add(d: 24h, to: today()))\n|> filter(fn:(r) => r._measurement == \"resultat-otpi\")\n|> filter(fn:(r) => r.location == \"France\")\n|> filter(fn:(r) => r._field == \"rendement\")"
    }
   ]
  },
  {
   "title": "Prix minimal",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\nfrom(bucket:\"price\")\r\n|> range(start: today(), stop: date.add(d: 24h, to: today()))\r\n|> filter(fn:(r) => r._measurement == \"cout-electricite\")\r\n|> filter(fn:(r) => r.location == \"France\")\r\n|> filter(fn:(r) => r._field == \"euros\")\r\n|> min()"
    }
   ]
  },
  {
   "title": "Prix  maximal",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\nfrom(bucket:\"price\")\r\n|> range(start: today(), stop: date.add(d: 24h, to: today()))\r\n|> filter(fn:(r) => r._measurement == \"cout-electricite\")\r\n|> filter(fn:(r) => r.location == \"France\")\r\n|> filter(fn:(r) => r._field == \"euros\")\r\n|> max()"
    }
   ]
  },
  {
   "title": "Période de charge et décharge",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 21, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket:\"price\")\n|> range(start: today(), stop: date.add(d: 24h, to: today()))\n|> filter(fn:(r) => r._measurement == \"resultat-otpi\")\n|> filter(fn:(r) => r.location == \"France\")\n|> filter(fn:(r) => r._field == \"statut-charge\")"
    }
   ]
  },
  {
   "title": "Coût total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket:\"price\")\n|> range(start: today(), stop: date.add(d: 24h, to: today()))\n|> filter(fn:(r) => r._measurement == \"resultat-otpi\")\n|> filter(fn:(r) => r.location == \"France\")\n|> filter(fn:(r) => r._field == \"prix-total\")"
    }
   ]
  },
  {
   "title": "Durée de l'opération",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket:\"price\")\n|> range(start: today(), stop: date.add(d: 24h, to: today()))\n|> filter(fn:(r) => r._measurement == \"resultat-otpi\")\n|> filter(fn:(r) => r.location == \"France\")\n|> filter(fn:(r) => r._field == \"duration-total\")"
    }
   ]
  }
 ]
}