# Generated by Django 4.1.7 on 2023-04-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asc_consomation', models.CharField(max_length=100)),
                ('asc_consomation_choices', models.IntegerField(choices=[(1, 'W'), (2, 'KW'), (3, 'MW'), (4, 'GW'), (5, 'TW')], default='1')),
                ('asc_tmp_min', models.CharField(max_length=100)),
                ('asc_tmp_min_choices', models.IntegerField(choices=[(1, 'Heure'), (2, 'Minute'), (3, 'Seconde')], default='1')),
                ('asc_capa_max', models.CharField(max_length=100)),
                ('asc_capa_max_choices', models.IntegerField(choices=[(1, 'Wh'), (2, 'KWh'), (3, 'MWh'), (4, 'GWh'), (5, 'TWh')], default='1')),
                ('asc_capa_actu', models.CharField(max_length=100)),
                ('asc_capa_actu_choices', models.IntegerField(choices=[(1, 'Wh'), (2, 'KWh'), (3, 'MWh'), (4, 'GWh'), (5, 'TWh')], default='1')),
                ('desc_consomation', models.CharField(max_length=100)),
                ('desc_consomation_choices', models.IntegerField(choices=[(1, 'W'), (2, 'KW'), (3, 'MW'), (4, 'GW'), (5, 'TW')], default='1')),
                ('desc_capa_max', models.CharField(max_length=100)),
                ('desc_capa_max_choices', models.IntegerField(choices=[(1, 'Wh'), (2, 'KWh'), (3, 'MWh'), (4, 'GWh'), (5, 'TWh')], default='1')),
                ('desc_capa_actu', models.CharField(max_length=100)),
                ('desc_capa_actu_choices', models.IntegerField(choices=[(1, 'Wh'), (2, 'KWh'), (3, 'MWh'), (4, 'GWh'), (5, 'TWh')], default='1')),
                ('target', models.CharField(max_length=100)),
                ('target_choices', models.IntegerField(choices=[(1, 'Wh'), (2, 'KWh'), (3, 'MWh'), (4, 'GWh'), (5, 'TWh')], default='1')),
                ('titre', models.CharField(max_length=100)),
            ],
        ),
    ]
