name: docker-image-ci-amd

on:
  push:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push python image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64/v8
          file: ./python.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ec2-python:latest
          
      - name: Build and push influxdb image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64/v8
          file: ./influxdb.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ec2-influxdb:latest

      - name: Build and push grafana image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64/v8
          file: ./grafana.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ec2-grafana:latest

      